#!/bin/bash
source $OPENSHIFT_REPO_DIR/misc/openshift/func
source $OPENSHIFT_REPO_DIR/misc/openshift/virtualenv

env | sed 's/[\%]/\\&/g;s/\([^=]*\)=\(.*\)/s%${\1}%\2%/' > $OPENSHIFT_TMP_DIR/sed.script

function expand_env_vars() {
    local SRC=$1
    local DEST=$2
    cat $SRC | sed -f $OPENSHIFT_TMP_DIR/sed.script > $DEST
}

function copy_templates() {
    msg_info "Creating uWSGI config..."
    if [ ! -d $UWSGI_DIR ]; then
        mkdir $UWSGI_DIR
    fi    
    expand_env_vars $TEMPLATES_DIR/uwsgi.ini $UWSGI_DIR/uwsgi.ini
    msg_info "Creating uWSGI config... done"

    msg_info "Creating nginx config..."
    expand_env_vars $TEMPLATES_DIR/nginx.conf $NGINX_DIR/conf/nginx.conf
    msg_info "Creating nginx config... done"
}

copy_templates
