#!/bin/bash
# AUX functions

export TERM=xterm-256color
red='\E[31m'
green='\E[32m'
yellow='\E[33m'
clear='\E[0m'

function msg_error() {
    echo -e $red"$@"$clear
}

function msg_success() {
    echo -e $green"$@"$clear
}

function msg_info() {
    echo -e $yellow"$@"$clear
}

function check_status() {
    if [ $1 -ne 0 ]; then
        msg_error "$2 failed"
        exit 1
    else
        msg_info "$2 done"
    fi
}
